### PR TITLE
Mek f3 63 send email on backend

### LINKED ISSUE #63: feat: f3(1)sendEmail-on-backend

### PR DESCRIPTION
**Pull request by mekdes45**
# Changes
    1. Create email service.
    2. Create email route.
    3. Install nodemailer to enable sending email.
    4. Add styles on scss.
    5. Add font awesome.
    6. Add env file
   
 # Purpose
    To send email for the app owner.
# Approach
    By adding contact address to send the email from customer to the app owner.
# Learning 
    How to use nodemailer and SMTP(Simple Mail Transfer Protocol).

 Closes #63

### CODE REVIEW

**Review by LeeTato — COMMENTED** [review]
It is good, but move the inline style to the style part to clean the code.

**Comment by ChelleAmon** [comment]
This is what I get after running your code after I put my email and password on env file

      [dev-server:*run]   response: '535-5.7.8 Username and Password not accepted. Learn more at\n' +
      [dev-server:*run]     '535 5.7.8  https://support.google.com/mail/?p=BadCredentials r7sm7494507qtw.25 - gsmtp',
      [dev-server:*run]   responseCode: 535,
      [dev-server:*run]   command: 'AUTH PLAIN'
      [dev-server:*run] }
      [dev-server:*run] [nodemon] app crashed - waiting for file changes before starting...

But in network >> request payload, I see all the information I inputted. So I guess, but not 100% sure it has something to do with my gmail account just blocking the incoming email?

**Review by sabiyoung — APPROVED** [review]
I put my email and password  in the env file. I was able to send an email successfully but the massage goes to Mekdes's email instead of my email in the env file. Other than that the code looks clean. Good job!

**Comment by ChelleAmon** [comment]
Good to know! Thank you, Saba for clarifying.

**Pull request merged**
