### PR TITLE
Mek 26 add email contact

### LINKED ISSUE #26: feat: f3(1) add email contact

### PR DESCRIPTION
**Pull request by mekdes45**
1.create contact-page component
2. create email Form control function 
3. style contact-page using scss
4. create sendEmail function 

closes #26

### CODE REVIEW

**Comment by ChelleAmon** [comment]
I switch the base branch to development just to make sure your branch will not merge to main later on.

Also, remove console.log on line 40 and 44 in component.ts

**Review by ChelleAmon — COMMENTED** [review]
I switch the base branch to development just to make sure your branch will not merge to main later on.

Also, remove console.log on line 40 and 44 in component.ts

**Review by sabiyoung — APPROVED** [review]
The front-end looks good. Hope you will going to add the backend later for full functionality.

**Review by svoggu — COMMENTED** [review]
code looks clean. Tried to run it and check ,but didn't see your route and rechecked in app-routing.module that it was not there.please add it so that can see your contact-page(email)

**Review by LeeTato — COMMENTED** [review]
looks great,. I did not see any error.

**Pull request merged**
