### PR TITLE
sv-43-49-nav-bar

### PR DESCRIPTION
**Pull request by svoggu**

### CODE REVIEW

**Comment by ChelleAmon** [comment]
Unable to run the code as this branch has merge conflict. I am unsure why there's a sidebar and a navbar?

**Comment by svoggu** [comment]
> Unable to run the code as this branch has merge conflict. I am unsure why there's a sidebar and a navbar?

I have to work on responsive navbar which may need sidebar, so i didnt delete that component.

**Comment by ChelleAmon** [comment]
> Unable to run the code as this branch has merge conflict. I am unsure why there's a sidebar and a navbar?

Are you going to create a separate issue for the sidebar?

**Review by ChelleAmon — APPROVED** [review]
Navbar looks much better and more responsive. Thank you for fixing it.

**Pull request merged**
