### PR TITLE
Gsa 151 display admin games data

### LINKED ISSUE #151: feat(f2)1: Display games data for admins
- Display games data on admin-games-list component 
-Should add some buttons to allow admins to makes changes to game details

### PR DESCRIPTION
**Pull request by ChelleAmon**
## Changes
_List Changes Introduced by this PR_
1. Add a table to show all games list 
2. Import Font Awesome module into the games module
3. Add a little bit of CSS styling
4. Dispatch all games from store

## Purpose
Admin will see a tabulated data of games list, allowing them to edit games and see the status 

## Learning

Closes #151

### CODE REVIEW

**Comment by ChelleAmon** [comment]
This will be ready for review when the other PR (create-admin-game-page) got approved and merged

**Review by brycejjacks — APPROVED** [review]
lol .. i love your PRs so much .. way to utilize the global scss this time and great job using the font awesome stuff .. amazing.. im the one the helped set that up and i dont even remember how to use it and here you are lol.. i even get a sneak peak into html tables .. which i have never used... great job 💪🏿

**Comment by ChelleAmon** [comment]
@brycejjacks Thank you lol! Just a heads up though, I did not use any global scss here, but I would love to work on it in the future. Aman and myself discussed about creating an issue for global scss but I prioritized other issues.

**Comment by brycejjacks** [comment]
@ChelleAmon lol i think you may have without even noticing.. if im not mistaken.. the "green" class type on line 25 is in the global styles .. you may have just gotten that from the other use of the font awsome stuff

**Comment by ChelleAmon** [comment]
Oh yeah I really did not notice the green class until now lol... @brycejjacks

**Pull request merged**
