### PR TITLE
feat(server):create and save user to database

### PR DESCRIPTION
**Pull request by svoggu**

### CODE REVIEW

**Review by sabiyoung — CHANGES_REQUESTED** [review]
In the server.is file number 88 and 89 has a different name (shape) than the user schema.

**Comment by ChelleAmon** [comment]
We want to be consistent with the shape of the user provided in Statement of Work. Here's my suggestion: 

**schema.ts**
- remove _name_ property
- insert the properties _first_ and _last_
- I am unsure with _role_ property but you might want to add it

**server.ts**
- on line 83 and from line 87-90, change _firstname_ to _first_, _lastname_ to _last_, and insert _username_

Check your user model.ts to make sure the shape is consistent there as well. 

Other than that, great job!

**Comment by svoggu** [comment]
> In the server.is file number 88 and 89 has a different name (shape) than the user schema.

Thanks for the suggestion. I did change in my code, but for some reason does not show up here. Will try to fix it.

**Comment by svoggu** [comment]
> We want to be consistent with the shape of the user provided in Statement of Work. Here's my suggestion:
> 
> **schema.ts**
> 
> * remove _name_ property
> * insert the properties _first_ and _last_
> * I am unsure with _role_ property but you might want to add it
> 
> **server.ts**
> 
> * on line 83 and from line 87-90, change _firstname_ to _first_, _lastname_ to _last_, and insert _username_
> 
> Check your user model.ts to make sure the shape is consistent there as well.
> 
> Other than that, great job!
Thanks for the suggestion. I did change in my code, but for some reason does not show up here. Will try to fix it.

**Comment by svoggu** [comment]
> We want to be consistent with the shape of the user provided in Statement of Work. Here's my suggestion:
> 
> **schema.ts**
> 
> * remove _name_ property
> * insert the properties _first_ and _last_
> * I am unsure with _role_ property but you might want to add it
> 
> **server.ts**
> 
> * on line 83 and from line 87-90, change _firstname_ to _first_, _lastname_ to _last_, and insert _username_
> 
> Check your user model.ts to make sure the shape is consistent there as well.
> 
> Other than that, great job!

And regarding properties which are in SOW, 5 of our group members discussed and Bryce who is doing login also suggested that the list in SOW is long and he wanted to use username and password in his login page and came to an agreement that username,firstname,lastname,email,role,password will be too many properties for registration page which i am taking care of as well. And regarding role we thought of adding later as none of us had clear idea about implementing it.

**Pull request closed without merging**
