### PR TITLE
patch(readme): change name to capitalize

### PR DESCRIPTION
**Pull request by vinsonf**

### CODE REVIEW

**Review by brycejjacks — APPROVED** [review]
One small change. Maybe name a more detailed description

**Review by Aman-codde — APPROVED** [review]
Looks good!

**Review by sirpuffin1 — APPROVED** [review]
Looks great. Knew you could do it. The capital "P" really brings it all together. :)

**Comment by svoggu** [comment]
Its a good thing to capitalize project names.

**Review by svoggu — CHANGES_REQUESTED** [review]
Its a good habit to capitalize project names.

**Review by LeeTato — COMMENTED** [review]
Capitalize the full name of the project; otherwise, use lowercase.

**Review by svoggu — APPROVED** [review]
I thought of considering leilt review.But for me Capitalizing is a good option.

**Comment by sabiyoung** [comment]
let me try to comment after merging

**Review by mekdes45 — APPROVED** [review]
looks great.

**Pull request merged**
