### PR TITLE
Bjj 40 unique username

### LINKED ISSUE #40: feat: f1 (2) unique username
the register page should check to see if the username is unique before saving to the database. there are many ways to do this. pick your poison.

### PR DESCRIPTION
**Pull request by brycejjacks**
## Changes
1. add functions to ask server if username is unique
2. add route in server to accept request
3. alert user if username is not unique

## Purpose
login in is based on username and password .. so username must be unique. usernames are created with register so there is where the changes must take place

Closes #40

### CODE REVIEW

**Comment by ChelleAmon** [comment]
I like the idea about debounce function and it's something I just learned from this branch. Since I can only see the function working by going to the network, is it possible that this can be seen by the client by adding an alert page or something like that? Hope this makes sense.

**Comment by sirpuffin1** [comment]
looks good and works great. I'd suggest using something like favicon or font awesome to add a little checkmark or x whenever the registration succeeds or fails

**Review by sirpuffin1 — APPROVED** [review]
whoops lol I almost messed it up. anyways. looks good and works great. I'd suggest using something like favicon or font awesome to add a little checkmark or x whenever the registration succeeds or fails

**Comment by brycejjacks** [comment]
> I like the idea about debounce function and it's something I just learned from this branch. Since I can only see the function working by going to the network, is it possible that this can be seen by the client by adding an alert page or something like that? Hope this makes sense.

yes i think that makes sense. now that it was so kindly merged by sirpuffin1. i'll add that to a later pr ... it will be just as angel suggested and you can tell that the function is running by when the check or X icon changes

**Comment by ChelleAmon** [comment]
Sounds good!

**Pull request merged**
